<a href="https://colab.research.google.com/github/juyounLee/Tensorflow2.0/blob/main/3_3_2_neuran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
rand = tf.random.uniform([2, 1], 0, 1)

In [4]:
rand

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.30131388],
       [0.7961557 ]], dtype=float32)>

In [5]:
rand1 = tf.random.uniform((1,), 0, 1)
rand1

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.04609144], dtype=float32)>

In [6]:
import math

def sigmoid(x):
  return 1 / (1+math.exp(-x))

In [7]:
x = 1
y = 0
w = tf.random.normal((1,), 0, 1)
output = sigmoid (w * x)
print(output)

0.3121134813211844


In [8]:
for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print(i, error, output, w) # i = 99, 199, 299, ..., 999 일때만 출력

99 -0.0862208030107988 0.0862208030107988 tf.Tensor([-2.3692997], shape=(1,), dtype=float32)
199 -0.04763460787745849 0.04763460787745849 tf.Tensor([-3.0001526], shape=(1,), dtype=float32)
299 -0.03265942953899694 0.03265942953899694 tf.Tensor([-3.3916829], shape=(1,), dtype=float32)
399 -0.02478390554726238 0.02478390554726238 tf.Tensor([-3.674943], shape=(1,), dtype=float32)
499 -0.01994515871804836 0.01994515871804836 tf.Tensor([-3.8966167], shape=(1,), dtype=float32)
599 -0.016676616345671847 0.016676616345671847 tf.Tensor([-4.078598], shape=(1,), dtype=float32)
699 -0.014323088589964962 0.014323088589964962 tf.Tensor([-4.232888], shape=(1,), dtype=float32)
799 -0.012548660097958166 0.012548660097958166 tf.Tensor([-4.3667684], shape=(1,), dtype=float32)
899 -0.0111635621208894 0.0111635621208894 tf.Tensor([-4.48499], shape=(1,), dtype=float32)
999 -0.01005262015448025 0.01005262015448025 tf.Tensor([-4.5908237], shape=(1,), dtype=float32)


In [9]:
# bias 
x = 0
y = 1
w = tf.random.normal((1,), 0, 1)
b = tf.random.normal((1,), 0, 1)

for i in range(1000):
  output = sigmoid(x*w + 1*b)
  error = y - output
  w = w + x*0.1*error
  b = b + 1*0.1*error

  if i%100 == 99:
    print(i, error, output)

99 0.12693957468770822 0.8730604253122918
199 0.058589212003853475 0.9414107879961465
299 0.037560694192261934 0.9624393058077381
399 0.027534375614019724 0.9724656243859803
499 0.021698557677613972 0.978301442322386
599 0.017889475793032572 0.9821105242069674
699 0.015210954580885394 0.9847890454191146
799 0.013226213041090507 0.9867737869589095
899 0.01169740769145533 0.9883025923085447
999 0.010483970151460076 0.9895160298485399
