<a href="https://colab.research.google.com/github/juyounLee/Tensorflow2.0/blob/main/3_3_3_neuran_network_true_or_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import math

In [2]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [3]:
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [1], [1], [0]])

In [4]:
w = tf.random.normal((2,), 0, 1)
b = tf.random.normal((1,), 0, 1)

for i in range(2000):
  sum_error = 0
  for j in range(4):
    output = sigmoid(np.sum(x[j]*w) + b)
    error = y[j][0] - output
    w = w + x[j]*0.1*error
    b = b + 1*0.1*error
    sum_error += error

  if i % 200 == 199:
    print(i, sum_error, w, b)


199 -0.0523669255457071 tf.Tensor([3.4099822 3.7021646], shape=(2,), dtype=float32) tf.Tensor([-1.217882], shape=(1,), dtype=float32)
399 -0.026393384201086195 tf.Tensor([4.85301   4.9338093], shape=(2,), dtype=float32) tf.Tensor([-1.9451251], shape=(1,), dtype=float32)
599 -0.017614695983806578 tf.Tensor([5.700054  5.7345767], shape=(2,), dtype=float32) tf.Tensor([-2.3731923], shape=(1,), dtype=float32)
799 -0.013178459066338272 tf.Tensor([6.3003373 6.3184886], shape=(2,), dtype=float32) tf.Tensor([-2.6767027], shape=(1,), dtype=float32)
999 -0.010508757606607973 tf.Tensor([6.76499  6.775728], shape=(2,), dtype=float32) tf.Tensor([-2.911464], shape=(1,), dtype=float32)
1199 -0.008729307194195964 tf.Tensor([7.143801 7.150632], shape=(2,), dtype=float32) tf.Tensor([-3.102674], shape=(1,), dtype=float32)
1399 -0.007460650503417474 tf.Tensor([7.463404 7.46797 ], shape=(2,), dtype=float32) tf.Tensor([-3.2638514], shape=(1,), dtype=float32)
1599 -0.006510790301333731 tf.Tensor([7.739719 7.7

In [5]:
print('w: {} b: {}'.format(w, b))

w: [8.2002735 8.201855 ] b: [-3.6349752]


In [6]:
for i in range(4):
  print('X: {} Y: {} Output: {:.3f}'.format(x[i], y[i], sigmoid(np.sum(x[i]*w) + b)))


X: [1 1] Y: [1] Output: 1.000
X: [1 0] Y: [1] Output: 0.990
X: [0 1] Y: [1] Output: 0.990
X: [0 0] Y: [0] Output: 0.026
