<a href="https://colab.research.google.com/github/juyounLee/Tensorflow2.0/blob/main/7_2_1_SimpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
x = []
y = []

for i in range(6):
  lst = list(range(i, i+4))

  # divide by 10 and store them
  # SimpleRNN에 각 timestep에 하나씩 숫자가 들어가기 때문에 여기서도 하나씩 분리해서 배열에 저장한다.
  x.append(list(map(lambda c:[c/10], lst)))

  # answer에 해당하는 4, 5 등의 정수 역시 앞에서처럼 10으로 나누어 저장함
  y.append((i+4)/10)

x = np.array(x)
y = np.array(y)

for i in range(len(x)):
  print(x[i], y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [7]:
model = tf.keras.Sequential([
                             tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4, 1]),
                             tf.keras.layers.Dense(1)
])

model.compile(optimizer='Adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x, y, epochs=100, verbose=0)
print(model.predict(x))

[[0.39635465]
 [0.5184458 ]
 [0.6251904 ]
 [0.71516657]
 [0.7890268 ]
 [0.8484899 ]]
